frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
// use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\User;
// use frontend\models\PasswordResetRequestForm;
// use frontend\models\ResetPasswordForm;
// use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\LoginForm;
use frontend\models\Registration;
use frontend\models\ChangePassword;
use frontend\models\AdminContacts;

//анкеты
use frontend\models\questionary\General;
use frontend\models\questionary\Agency;
use frontend\models\questionary\Designer;
use frontend\models\questionary\Models;
use frontend\models\questionary\Photographer;

/**
 * Site controller
 */
class SiteController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (($action->id == 'settings') &&
            ($action->id == 'login')) {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {


        $contactForm = new ContactForm;
        $contactFormItems = $contactForm->getCategoryQuestions();
        $contactFormOk = FALSE;

        if ($contactForm->load(Yii::$app->request->post()) && $contactForm->validate()) {
            if($contactForm->sendEmail()){
                $contactFormOk = TRUE;
            } else{
                die('ошибка при отправке письма');
            }
        }

        $user = new Registration;
        return $this->render('index', [
            'contactForm'       => $contactForm,
            'contactFormItems'  => $contactFormItems,
            'contactFormOk'     => $contactFormOk,

            'registration' => $user,
            'accountsType' => $user->getAccountsType(),
            'sel_profs'    => $user->sel_profs()
        ]);
    }

    /*
    * Registration new User
    *
    */
    public function actionRegistration()
    {
        $user = new Registration;
        // var_dump(Yii::$app->request->post()); die();
        if (!($user->load(Yii::$app->request->post()) && $user->registration())) {
            return print_r($user->getErrors());
        }
        return $this->redirect('../settings');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    // public function actionLogout()
    // {
    //     Yii::$app->user->logout();

    //     return $this->goHome();
    // }



    /**
     * Signs user up.
     *
     * @return mixed
     */
    // public function actionSignup()
    // {
    //     $model = new SignupForm();
    //     if ($model->load(Yii::$app->request->post())) {
    //         if ($user = $model->signup()) {
    //             if (Yii::$app->getUser()->login($user)) {
    //                 return $this->goHome();
    //             }
    //         }
    //     }

    //     return $this->render('signup', [
    //         'model' => $model,
    //     ]);
    // }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    // public function actionRequestPasswordReset()
    // {
    //     $model = new PasswordResetRequestForm();
    //     if ($model->load(Yii::$app->request->post()) && $model->validate()) {
    //         if ($model->sendEmail()) {
    //             Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

    //             return $this->goHome();
    //         } else {
    //             Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
    //         }
    //     }

    //     return $this->render('requestPasswordResetToken', [
    //         'model' => $model,
    //     ]);
    // }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    // public function actionResetPassword($token)
    // {
    //     try {
    //         $model = new ResetPasswordForm($token);
    //     } catch (InvalidParamException $e) {
    //         throw new BadRequestHttpException($e->getMessage());
    //     }

    //     if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
    //         Yii::$app->session->setFlash('success', 'New password was saved.');

    //         return $this->goHome();
    //     }

    //     return $this->render('resetPassword', [
    //         'model' => $model,
    //     ]);
    // }





    //Добавленные страниц
    public function actionQuestionary()
    {
        $general = new General();

        $agency = FALSE;
        $designer = FALSE;
        $models = FALSE;
        $photographer = FALSE;


        // $agency = new Agency();
        // $designer = new Designer();
        // $models = new Models();
        $photographer = new Photographer();

        return $this->render('questionary', [
            'general' => $general,
            'models' => $models,
            'photographer' => $photographer,

            'agency' => $agency,
            'designer' => $designer
            ]);
    }

    public function actionAlbum()
    {
        return $this->render('album');
    }

    public function actionJournal()
    { //Нужно подключить css

        return $this->render('journal');
    }

    // public function actionVisitor()
    // {
    //     // $this->layout('visitor');
    //     // var_dump( $this->layout);die();
    //     return $this->render('settings');   //переработать!!!
    // }

    public function actionSearch()
    {
        return $this->render('search');
    }

    public function actionSettings()
    {
        $msg  = "";
        if ($post = Yii::$app->request->post()) {
            $form = $post['Users'];
            $password_form = ChangePassword::findIdentity(Yii::$app->user->getId());
            $password_form->old_password = $form['old_password'];
            $password_form->new_password = $form['new_password'];
            $password_form->new_password_repeat = $form['repeat_password'];
            if (!$msg = $password_form->change()) {
                $msg = "Пароль успешно изменен";
            }
        }
        return $this->render('settings', [
            'msg' => $msg]);
    }

    // public function actionChangepassword()
    // {
    //     $form = Yii::$app->request->post()['Users'];

    //     $password_form = ChangePassword::findIdentity(Yii::$app->user->getId());
    //     // var_dump($password_form);die();
    //     $password_form->old_password = $form['old_password'];
    //     $password_form->new_password = $form['new_password'];
    //     $password_form->new_password_repeat = $form['repeat_password'];
    //     if (!$msg = $password_form->change()) {
    //         $msg = "Пароль успешно изменен";
    //     }
    //     return $this->render('settings', ['msg' => $msg]);
    // }

    public function actionEvents()
    {
        return $this->render('events');
    }

    public function actionVacancies()
    {
        return $this->render('vacancies');
    }

    public function actionSubscription()
    {
        return $this->render('subscription');
    }

    public function actionRecommendations()
    {
        return $this->render('recommendations');
    }

    // public function actionMypage() // переделать по ID
    // {
    //     return $this->render('mypage');
    // }

    public function actionMypage()
    {

    }



}

frontend/views/layouts/_main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
        ['label' => 'About', 'url' => ['/site/about']],
        ['label' => 'Contact', 'url' => ['/site/contact']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/main.php
<?php

use yii\helpers\Url;
use frontend\assets\AppAsset;

AppAsset::register($this);

$this->beginPage() ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php $this->head() ?>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="language" content="<?= Yii::$app->language ?>">
	<link href="http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300" rel="stylesheet" type="text/css">
	<link rel="icon" href="favicon.ico" type="image/x-icon">
	<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
	<title>МодаVisitor</title>
	<meta name="keywords" content="key index">
	<meta name="description" content="des index">
	<!-- <link rel="stylesheet" href="/fonts/awesome/css/font-awesome.min.css"> -->
	<!--[if IE 7]>
		<link rel="stylesheet" href="/fonts/awesome/css/font-awesome-ie7.min.css">
	<![endif]-->

</head>
<body>
<?php $this->beginBody() ?>
<div class="container">
	<div class="head" style="<?php echo (Yii::$app->controller->id == 'site' && Yii::$app->controller->action->id == 'index') ? 'position:fixed;':'';?>">
		<div class="lang">
            <a style="color:#fff;" href="<?= Url::to(['site/language', 'id'=>'en']);?>"><div class='lang_N tlanguage' data='N'>en</div></a>
            <a style="color:#fff;" href="<?= Url::to(['site/language', 'id'=>'ru']);?>"><div class='lang_Y tlanguage' data='Y'>ru</div></a>
            <a style="color:#fff;" href="<?= Url::to(['site/language', 'id'=>'fr']);?>"><div class="lang_N tlanguage" data="N">fr</div></a>
            <a style="color:#fff;" href="<?= Url::to(['site/language', 'id'=>'ch']);?>"><div class="lang_N tlanguage" data="N">ch</div></a>
		</div>
		<div class="title">
			<a class="logo" href="/">
				<span class="slogan"> эксклюзивная презентация в сети</span>
			</a>
			<div class="clear"></div>
		</div>

        <?php if (Yii::$app->user->isGuest) {?>
		<div class="menu1" id="top-menu">
			<ul>
				<li class="active">
					<a href="#b1">ДОМОЙ</a>
				</li>
				<li>
					<a href="#b2">О НАС</a>
				</li>
				<li>
					<a href="#b3">ПРЕИМУЩЕСТВА</a>
				</li>
				<li>
					<a href="#b4">КОМАНДА</a>
				</li>
				<li>
					<a href="#b5">ЦЕНОВЫЕ ПАКЕТЫ</a>
				</li>
				<li>
					<a href="#b6">СВЯЖИТЕСЬ С НАМИ</a>
				</li>
			</ul>
				<div class="clear"></div>
		</div>

        <?php } else {?>
        <div class="c-navigation">
			<div class="c-nav-text" style="margin-right: 20px;">
				<p><a href="<?= Url::to(['site/profile', 'id'=> Yii::$app->user->id]);?>">
					<!--
						задание от Александра 20160811:
						В шапке справа, вместо логина/мейла надпись "Мой профиль".
					-->
					Мой профиль
					<?= Yii::$app->user->identity->first_name ?>
				</a></p>
				<p><a href="<?= Url::to(['site/settings']) ?>">Настройки</a>&nbsp;
                                    <a href="<?= Url::to(['site/logout']);?>">Выход</a></p>
			</div>
			<!-- <div class="c-nav-img">
                             <?php if (!empty(Yii::$app->user->avatar)){?>
				<img style="width:40px;" id="avatar_img_small" alt="Фотография профиля" src="../img_avatar_small/no_avatar.png">
                             <?php } ?>
			</div> -->
		</div>
                <?php }?>
	</div>
	<div class="content">
             <?php echo $content;?>
        </div>



	</div>

        <?php if (!(Yii::$app->controller->id == 'site' && Yii::$app->controller->action->id == 'index')){?>
        <div class="footer">
                <a href="/write">
                        <i aria-hidden="true" class="fa fa-4x fa-pencil-square-o"></i>
                        <br>write to us
                </a>
                <a href="/about">
                        <i aria-hidden="true" class="fa fa-4x fa-info-circle"></i>
                        <br>about us
                </a>
                <a href="/services">
                        <i aria-hidden="true" class="fa fa-4x fa-cogs"></i>
                        <br>our services
                </a>
                <a href="/mentors">
                        <i aria-hidden="true" class="fa fa-4x fa-users"></i>
                        <br>our mentors
                </a>
                <a href="/faq">
                        <i aria-hidden="true" class="fa fa-4x fa-question-circle"></i>
                        <br>faq
                </a>
                <a href="/contacts">
                        <i aria-hidden="true" class="fa fa-4x fa-envelope-o"></i>
                        <br>contacts
                </a>
        </div>
    <?php } ?>

<script>
// Cache selectors
var lastId,
	topMenu = $("#top-menu"),
	topMenuHeight = topMenu.outerHeight()+15,
	// All list items
	menuItems = topMenu.find("a"),
	// Anchors corresponding to menu items
	scrollItems = menuItems.map(function(){
		var item = $($(this).attr("href"));
		if (item.length) { return item; }
	});
</script>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>